### Application ###
applicationVersion=0.0.1-SNAPSHOT

### Project ###
projectGroup=com.meteor
javaVersion=21

### Gradle plugins ###
asciidoctorConvertVersion=4.0.5
springJavaFormatVersion=0.0.47

### Spring ###
springBootVersion=4.1.0
springDependencyManagementVersion=1.1.7
springCloudDependenciesVersion=2025.1.2

### External libraries ###
sentryVersion=8.43.2
archUnitVersion=1.4.1
